config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :words
  root to: redirect('/words')
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:name, :title, :description, :entry_type, :pronunciation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myword</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>
      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl>
    <dt><%= f.label :name %></dt>
    <dd><%= f.text_field :name, placeholder: '単語', maxlength: 20, size: 30 %></dd>
    <dt><%= f.label :title %></dt>
    <dd><%= f.text_field :title, placeholder: '意味', maxlength: 100, size: 30 %></dd>
    <dt><%= f.label :pronunciation %></dt>
    <dd><%= f.text_field :pronunciation, placeholder: '読み', maxlength: 60 %></dd>
    <dt><%= f.label :description %></dt>
    <dd><%= f.text_area :description, placeholder: '詳細', cold: 30, rows: 10 %></dd>
    <%= f.hidden_field :entry_type, value: 'Notation' %>
    <%= f.button :submit %>
  </dl>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>
<article>
  <%= render 'form' %>
</article>
<footer class="cf">
  <% if user_signed_in? %>
    <div class="r">
      <%= link_to 'Show', @word %> |
      <%= link_to 'Destroy', @word, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>
  <div class="l">
    <%= link_to 'Back', words_path %>
  </div>
</footer>

app/views/words/index.html.erb
<h1>開発に使える英単語</h1>
<p><%= link_to "by tokimari", "https://github.com/tokimari" %></p>
<article>
  <header>
    <p>英語がからきし駄目なtokimariのお勉強用に、社内日報で配信している英単語録です。</p>
    <p>Dash用ドックセットで使えるスクリプトは<%= link_to "こちら", "https://github.com/tokimari/mywords" %>で配布しています。</p>
  </header>
  <section>
    <ol>
      <% @words.each do |word| %>
        <li><%= link_to word.name, word %> - <%= word.title %></li>
      <% end %>
    </ol>
  </section>
</article>
<footer class="tr">
  <%= link_to 'New Word', new_word_path if user_signed_in? %>
</footer>

app/views/words/new.html.erb
<h1>New word</h1>
<article>
  <%= render 'form' %>
</article>
<footer class="tl">
  <%= link_to 'Back', words_path %>
</footer>

app/views/words/show.html.erb
<article id="<%= @word.id %>">
  <header>
    <h1>
      #<%= @word.id %>
      <%= @word.name %>
      <small>♪<%= @word.pronunciation %></small>
    </h1>
    <p><%= @word.title %></p>
  </header>
  <section>
    <%= @word.description.html_safe %>
  </section>
</article>
<footer class="cf">
  <% if user_signed_in? %>
    <div class="r">
      <%= link_to 'Edit', edit_word_path(@word) %> |
      <%= link_to 'Destroy', @word, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>
  <div class="l">
    <%= link_to 'Back', words_path %>
  </div>
</footer>